### ISSUE TITLE
Why the scripts is calling a remote url? Why the rclone is not a official release?

### ISSUE THREAD

**Issue by rudnypc** [developeranaz/test2#16]
i'm a little scared, why not use the official rclone and why are you calling a url in entrypoint?

Sorry for the question, but I've seen projects trying to make a botnet using a real problem.

**Comment by developeranaz** [comment]
> i'm a little scared, why not use the official rclone and why are you calling a url in entrypoint?
> 
> Sorry for the question, but I've seen projects trying to make a botnet using a real problem.

Don't be afraid, here the version of rclone i'mm using is official but an older release. The version i'mm using is much stable for serving to web.

**Comment by developeranaz** [comment]
# Why the scripts is calling a remote url? 
I didn't mean to take other people's data, first I added that to remotely change this index template and that failed. You can remove it.

**Comment by developeranaz** [comment]
> # Why the scripts is calling a remote url?
> I didn't mean to take other people's data, first I added that to remotely change this index template and that failed. You can remove it.

If i remove that it may screw the entire app, i'll cleanup the code later 😅
