### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by emrecan-balgun** [developeranaz/test2#23]
![image](https://user-images.githubusercontent.com/56371000/141493514-74ab4ca2-5f0b-41af-8e56-b16f3e442297.png)

My account information is correct and 2 factor verification is turned off. But I still get the error, what is the reason?

**Comment by developeranaz** [comment]
I don't know for sure what's wrong.
Maybe the mega.nz servers are down, please wait and try to restart the dynos in heroku.

If you are still facing issues try a different mega account.
