### ISSUE TITLE
Folder problem.

### ISSUE THREAD

**Issue by ThereBum** [developeranaz/test2#24]
I can't download a folder with one click.I think i need to download files one by one but there are too many.

Are there any solution to download folders?

**Comment by developeranaz** [comment]
1. foldered download is't possible

2. but you can scrap all link using any scrapers (folder inside folder is't possible using this method)

3. use rclone, it is the perfect solution for copying or downloading folder inside folder from your mega to your device

**Comment by ThereBum** [comment]
Do i need to create an account on Zeet to use rclone?
I don't know much about the rclone thing.

**Comment by developeranaz** [comment]
No just rclone, with a device
which OS  are you using?

**Comment by developeranaz** [comment]
and total size of your folder?

**Comment by ThereBum** [comment]
Windows and i have 20 and 50 gb folders.

**Comment by developeranaz** [comment]
> Windows and i have 20 and 50 gb folders.

is that a mega premium/pro user

**Comment by ThereBum** [comment]
no it's not, i was trying to download them without limit with heroku.

**Comment by developeranaz** [comment]
> no it's not, i was trying to download them without limit with heroku.

sorry quota bypass is not possible for folder

by using rclone you can actually copy/download files but for quota bypass you need to use different IPs (after every quota bypass need to change ip ) no other way

**Comment by ThereBum** [comment]
Then if i use the heroku method and download everything in folders one by one, i won't face the quota bypass right?

**Comment by developeranaz** [comment]
no quota bypass is hard , it is only usefully applicable for large single files. 
This index allows you to download files through any download managers - in this method you can pause your download if quota is exceeded then wait heroku's ip changes() or by restarting dynos you can resume your download an this process is repeatedly.

**Comment by developeranaz** [comment]
another way is to creating multiple indexes using heroku account and then taking multiple links of the same file and mirror link download using aria2 or FDM. They are harder for multiple files.

**Comment by ThereBum** [comment]
Ok, i get it.
Thanks for the help.
