### ISSUE TITLE
There's nothing here, yet. issue  show when i open app

### ISSUE THREAD

**Issue by IGuruDevI** [developeranaz/test2#26]
i have seeing msg when i build app and open it . it do  not show mega nz files. pls check it

**Comment by developeranaz** [comment]
let me check

**Comment by developeranaz** [comment]
i had tested and it is working fine
Please verify that your email and password are correct in configvars settings for heroku webapp.

Another reason could be two-factor authentication in Mega. You need to disable it.

if you are still facing issues then try using a different mega account

**Comment by IGuruDevI** [comment]
I think something was wrong with a video that I imported into my account so I have deleted those videos and imported new videos now I can see the root directory after making the app. thanks for the reply bro. nice work :)
