### ISSUE TITLE
Item could not be created

### ISSUE THREAD

**Issue by NicoPuebla** [developeranaz/test2#29]
I tried to deploy the app but it's say "Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

It's not working anymore?

**Comment by NicoPuebla** [comment]
![image](https://user-images.githubusercontent.com/96320208/146624694-be71d0d8-6299-4419-87de-80944475b059.png)

It's working again the deploy, but it's not working the app itself

**Comment by developeranaz** [comment]
I think i did fixed this #28 two days ago.
And now i deployed this application for testing and its working fine.

- Try depoy again [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/developeranaz/Mega.nz-Rclone-Index-V3.01)

- Double check your email and password .
- Makesure 2factor authentication is disabled.
- If still not working use other mega account.

**Comment by NicoPuebla** [comment]
It's working, the issue was my account, I created a new one and now is working correctly, thanks
