### ISSUE TITLE
Error in heroku

### ISSUE THREAD

**Issue by Phury69** [developeranaz/test2#30]
Error: Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

**Comment by developeranaz** [comment]
> Error: Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

Again
I think i did fixed this #28 three days ago.
And now i deployed this application for testing and its working fine.

- Try depoy again [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/developeranaz/Mega.nz-Rclone-Index-V3.01)


https://github.com/developeranaz/Mega.nz-Rclone-Index-V3.01/issues/29#issuecomment-997136087

**Comment by Phury69** [comment]
I check again and its working now Great job dude
