### ISSUE TITLE
not able to create new app at herko 

### ISSUE THREAD

**Issue by raka334** [developeranaz/test2#31]

**Comment by raka334** [comment]
not able to use this app help

**Comment by developeranaz** [comment]
they keep blocking my app ☹️
Again, i renamed this app 
its now working fine. and please redeploy it.

**Comment by xv6c88** [comment]
Create app
App creation failed. Please ensure you have valid values in the above form fields.

**Comment by developeranaz** [comment]
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/843DCF1D5BC45F4572F151A9FC1516437A042A7CC6F979F8B1F1F164AB691D07)

Try deploy using the above Button, above button is working

**Comment by xv6c88** [comment]
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

**Comment by xv6c88** [comment]
README.md

**Comment by developeranaz** [comment]
i know that heroku is blocking web app named @developeranaz , so start deploy from this issue page

**Comment by developeranaz** [comment]
if i did post this working button in my readme they will again flag me as violation, and i'll fix my readme soon. Currently i'mm rewriting this repository from docker to pure python

**Comment by xv6c88** [comment]
Thank you for finding the problem.

**Comment by xv6c88** [comment]
Reminder: Heroku has banned this project, please fork this project and replace Lbingyi in README.md with your username before deploying

**Comment by xv6c88** [comment]
Need to be modified by the user
