### ISSUE TITLE
Blocked by heroku 

### ISSUE THREAD

**Issue by mackreal** [developeranaz/test2#32]
Title is self-explanatory, it says that the source code violates salesforce policy.

**Comment by developeranaz** [comment]
I don't know why heroku keeps blocking my app.
Again, I renamed the app and it works now
Alternative way : you can use [HEROKU-RCLONE-SERVE-INDEX](https://github.com/developeranaz/HEROKU-RCLONE-SERVE-INDEX), heroku does not say any violation for [this](https://github.com/developeranaz/HEROKU-RCLONE-SERVE-INDEX) app and they both share the same.

**Comment by developeranaz** [comment]
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/6008C17A2570649AE4E85D00033E8569856DF077814B3334E2A6C5ED667BD246)

This button may not be able to work after a few hours or days.
Heroku will set a violation for this button as well hurry up
