### ISSUE TITLE
blocked by heroku again

### ISSUE THREAD

**Issue by ghost** [developeranaz/test2#34]
this is blocked even though its renamed. Is there any other way to do this?

**Comment by developeranaz** [comment]
Sorry,  i am not able to deploy my app in Heroku. You might be able to [download my source code here](https://github.com/developeranaz/Mega.nz-Rclone-Index-V3.03/archive/refs/heads/main.zip) and then upload it to your github account and try to deploy with your hosted github using your git repository you might have a chance to work my webapp for a few more days.
In case of any problem with your deployment, you can post the issues here.

**Comment by Valstrax002** [comment]
hi I'm trying to deploy same app with my account but, I'm new to programming. So, I made app in heroku and connected branch with my account, when I start to deploy app under deploy session on app, log says 
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed
 
this all the time I tried, what should I change to deploy?

**Comment by developeranaz** [comment]
Wait,
please don't use heroku-cli if you don't know how to use it. Use deployment from your git.

**Comment by developeranaz** [comment]
maybe i'll create a new github account, 
i don't know it will last or not . 
and i'll post that deployment button here wait ☹️

**Comment by developeranaz** [comment]
> hi I'm trying to deploy same app with my account but, I'm new to programming. So, I made app in heroku and connected branch with my account, when I start to deploy app under deploy session on app, log says -----> Building on the Heroku-20 stack -----> Determining which buildpack to use for this app ! No default language could be detected for this app. HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically. See https://devcenter.heroku.com/articles/buildpacks ! Push failed
> 
> this all the time I tried, what should I change to deploy?

Try this deployment button as fast as you can.

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/6008C17A2570649AE4E85D00033E8569856DF077814B3334E2A6C5ED667BD246)

This button may not be able to work after a few hours or days.
Heroku will set a violation for this button as well, so hurryup

**Comment by Valstrax002** [comment]
thankyou, it is great and best app for mega I have seen, now I have to look for other way.... Thank you for the app

**Comment by developeranaz** [comment]
> thankyou, it is great and best app for mega I have seen, now I have to look for other way.... Thank you for the app

One way or another I will continue to support this app.
I'm currently completely rebuilding this app from docker to pure python, and it will work better than docker, especially since it will improve speed and stability.
