### ISSUE TITLE
facing deploy app

### ISSUE THREAD

**Issue by heyjishh** [developeranaz/test2#36]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

can you please justify me what is it.

**Comment by developeranaz** [comment]
> We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
> 
> can you please justify me what is it.

I do not know why. The source code is clean, maybe some users served pirated indexes or other, so heroku put a violation to my source code.

**Comment by developeranaz** [comment]
You might be able to [download my source code here](https://github.com/developeranaz/Mega.nz-Rclone-Index-V3.03/archive/refs/heads/main.zip) and then upload it to your github account and try to deploy with your hosted github using your git repository (heroku button method)you might have a chance to work my webapp for a few more days.
In case of any problem with your deployment, you can post the issues here.

**Comment by developeranaz** [comment]
Or else

 [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/843DCF1D5BC45F4572F151A9FC1516437A042A7CC6F979F8B1F1F164AB691D07)

Try deploy using the above Button, above button is working

**Comment by balasubramanian1612s** [comment]
Can you provide me the new deploy link? Thanks!

**Comment by developeranaz** [comment]
1. fork this repository
2. then deploy using the below similar link 
3. https://dashboard.heroku.com/new?template=https://github.com/YOURGITHUBUSERNAME/Mega-Rclone-Index-v3

replace YOURGITHUBUSERNAME to your own github username

**Comment by developeranaz** [comment]
fixed
