### ISSUE TITLE
extremely slow download

### ISSUE THREAD

**Issue by himynameiszim** [developeranaz/test2#37]
my download really slow, its running arround 600kbs using idm and 7-800kbs using xdm? i really consider this not fast at all, any solutions?

**Comment by developeranaz** [comment]
Some files are slow, I cannot fully increase the speed that may be set by mega.
But there are some ways to increase the speed a bit.
1. Use multiple threads, I assume you've already done this step.
2. Go to mega.nz >sign in your account > settings >transfers > set `Number of parallel download connections` to max (use PC or desktop mode )
3. Use a different server US or Europe

**Comment by developeranaz** [comment]
If the above steps are not enough, please download with the help of the term `mirror download`
This Feature is available on FDM, I don't know it's available on XDM please check it.

1. Create/deploy multiple index [2to3+] of same mega account.
2. Copy links of same file from multiple indexes.
3. then download the file from different index, using mirror link download feature. [in case of FDM - add a one link to downloads after the download starts , right click on the downloading file in fdm > to `add mirror` option > paste next mirror link > ok]

![WHfM3cOgVW](https://user-images.githubusercontent.com/71500526/138307264-6d021588-a654-41b4-a6bc-bbd256d7906a.gif)

This trick multiplies your existing speed.

**Comment by developeranaz** [comment]
If it works for you, please comment here. May help improve this repository and others who use this repository

**Comment by ghost** [comment]
The thread is not complete yet... Even as a pro subscriber... I can have value for money just because mega limits speeds.
