### ISSUE TITLE
application error 

### ISSUE THREAD

**Issue by fernandom241** [developeranaz/test2#39]
![image](https://user-images.githubusercontent.com/77253799/153689149-93208001-17cc-471a-b488-93f68d19fbea.png)

**Comment by developeranaz** [comment]
Try restart dynos

**Comment by fernandom241** [comment]
application error still pops up

**Comment by developeranaz** [comment]
My mega account is working. Makesure your Mega account's two factor auth is off,
or try testing with another mega account, i'll suggest to create a new account for testing.

**Comment by fernandom241** [comment]
thanks, it works when I test with another mega account

**Comment by developeranaz** [comment]
> thanks, it works when I test with another mega account

Some Mega accounts are not recognized by rclone.
