### ISSUE TITLE
source code voilates the saleforce

### ISSUE THREAD

**Issue by Luciferarjun25** [developeranaz/test2#40]
It was working fine, but now, when I try to deploy app, I see message: Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy

**Comment by Luciferarjun25** [comment]
Unknown Error. Please contact support.

**Comment by developeranaz** [comment]
> Unknown Error. Please contact support.

Thats heroku's mistake you should try again after sometime, or use other heroku account. make sure you are deploying from my latest repository [this](https://github.com/developeranaz/Mega-index-heroku) or use the button below
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://developeranaz.github.io/Mega-index-heroku/random.html)
I did tested yesterday by deploying my own app using this button, its working.
